In [1]:
!pip install statsbombpy

Collecting statsbombpy
  Downloading statsbombpy-1.22.0-py3-none-any.whl.metadata (63 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.8/63.8 kB 3.0 MB/s eta 0:00:00
Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (from statsbombpy) (2.2.3)
Requirement already satisfied: requests in /usr/local/lib/python3.13/dist-packages (from statsbombpy) (2.32.4)
Collecting requests-cache (from statsbombpy)
  Downloading requests_cache-1.3.3-py3-none-any.whl.metadata (9.4 kB)
Requirement already satisfied: inflect in /usr/local/lib/python3.13/dist-packages (from statsbombpy) (7.5.0)
Requirement already satisfied: joblib in /usr/local/lib/python3.13/dist-packages (from statsbombpy) (1.6.0)
Requirement already satisfied: more_itertools>=8.5.0 in /usr/local/lib/python3.13/dist-packages (from inflect->statsbombpy) (10.8.0)
Requirement already satisfied: typeguard>=4.0.1 in /usr/local/lib/python3.13/dist-packages (from inflect->statsbombpy) (4.6.0)
Requirement already satisfied: cloudpickle>=3.0 in /usr/local/lib/python3.13/dist-packages (from joblib->statsbombpy) (3.1.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas->statsbombpy) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas->statsbombpy) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas->statsbombpy) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas->statsbombpy) (2026.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests->statsbombpy) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests->statsbombpy) (3.19)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests->statsbombpy) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests->statsbombpy) (2026.7.22)
Requirement already satisfied: attrs>=21.2 in /usr/local/lib/python3.13/dist-packages (from requests-cache->statsbombpy) (26.1.0)
Collecting cattrs>=22.2 (from requests-cache->statsbombpy)
  Downloading cattrs-26.2.0-py3-none-any.whl.metadata (8.5 kB)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests-cache->statsbombpy) (4.11.7)
Collecting url-normalize>=2.0 (from requests-cache->statsbombpy)
  Downloading url_normalize-3.0.0-py3-none-any.whl.metadata (7.5 kB)
Requirement already satisfied: typing-extensions>=4.14.0 in /usr/local/lib/python3.13/dist-packages (from cattrs>=22.2->requests-cache->statsbombpy) (4.16.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas->statsbombpy) (1.17.0)
Downloading statsbombpy-1.22.0-py3-none-any.whl (18 kB)
Downloading requests_cache-1.3.3-py3-none-any.whl (70 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 70.8/70.8 kB 3.6 MB/s eta 0:00:00
Downloading cattrs-26.2.0-py3-none-any.whl (74 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 74.8/74.8 kB 3.0 MB/s eta 0:00:00
Downloading url_normalize-3.0.0-py3-none-any.whl (16 kB)
Installing collected packages: url-normalize, cattrs, requests-cache, statsbombpy
Successfully installed cattrs-26.2.0 requests-cache-1.3.3 statsbombpy-1.22.0 url-normalize-3.0.0

In [2]:
import pandas as pd
from statsbombpy import sb
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import math

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import os

GOOGLE_DRIVE_PATH = "/content/drive/MyDrive/statsbomb_data"
FILE_PATH = os.path.join(GOOGLE_DRIVE_PATH, "all_statsbomb_shots.csv")

def concat_to_one_df(competitions, file_path=FILE_PATH): # funkcja zebysmy mogli sobie zapisać pełengo dataframe'a, bo tworzenie go za każdym razem trwałoby około 40/50 minut (NIE PYTAJ SKĄD WIEM XDDD)
    os.makedirs(os.path.dirname(file_path), exist_ok=True)

    if os.path.exists(file_path):
        os.remove(file_path)

    is_first_match = True

    for c_id, s_id in zip(competitions['competition_id'], competitions['season_id']):

        current_match_df = sb.matches(competition_id=c_id, season_id=s_id)

        for m_id in current_match_df['match_id']:
            current_events_df = sb.events(match_id=m_id)
            shot_df = current_events_df[current_events_df['type'] == 'Shot'].copy()

            if not shot_df.empty:
                shot_df['match_id'] = m_id

                if is_first_match:
                    shot_df.to_csv(file_path, index=False)
                    is_first_match = False
                else:
                    first_row = pd.read_csv(file_path, nrows=0)
                    shot_df = shot_df.reindex(columns=first_row.columns)
                    shot_df.to_csv(file_path, mode='a', header=False, index=False)

In [ ]:
competitions = sb.competitions()
df_to_check = concat_to_one_df(competitions)

Strumieniowane dane wyjściowe obcięte do 5000 ostatnich wierszy.
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

In [10]:
import os
GOOGLE_DRIVE_PATH = "/content/drive/MyDrive/statsbomb_data"
FILE_PATH = os.path.join(GOOGLE_DRIVE_PATH, "all_statsbomb_shots.csv")

shots_df = pd.read_csv(FILE_PATH)

In [11]:
shots_df

,50_50,ball_receipt_outcome,ball_recovery_offensive,ball_recovery_recovery_failure,block_deflection,block_offensive,carry_end_location,clearance_aerial_won,clearance_body_part,clearance_head,...,substitution_outcome,substitution_outcome_id,substitution_replacement,substitution_replacement_id,tactics,team,team_id,timestamp,type,under_pressure
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Bayer Leverkusen,904,00:02:13.090,Shot,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Bayer Leverkusen,904,00:05:53.050,Shot,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Bayer Leverkusen,904,00:06:30.028,Shot,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Bayer Leverkusen,904,00:10:19.546,Shot,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Bayer Leverkusen,904,00:14:54.051,Shot,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101222,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,United States Women's,1214,00:14:29.178,Shot,NaN
101223,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,United States Women's,1214,00:19:07.871,Shot,NaN
101224,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Spain Women's,863,00:19:59.455,Shot,True
101225,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,United States Women's,1214,00:30:36.196,Shot,NaN
101226,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,United States Women's,1214,00:33:35.925,Shot,True

In [14]:
shots_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101227 entries, 0 to 101226
Data columns (total 91 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   50_50                           0 non-null       float64
 1   ball_receipt_outcome            0 non-null       float64
 2   ball_recovery_offensive         0 non-null       float64
 3   ball_recovery_recovery_failure  0 non-null       float64
 4   block_deflection                0 non-null       float64
 5   block_offensive                 0 non-null       float64
 6   carry_end_location              0 non-null       float64
 7   clearance_aerial_won            0 non-null       float64
 8   clearance_body_part             0 non-null       float64
 9   clearance_head                  0 non-null       float64
 10  clearance_left_foot             0 non-null       float64
 11  clearance_right_foot            0 non-null       float64
 12  counterpress                    0 non-null       float64
 13  dribble_nutmeg                  0 non-null       float64
 14  dribble_outcome                 0 non-null       float64
 15  dribble_overrun                 0 non-null       float64
 16  duel_outcome                    0 non-null       float64
 17  duel_type                       0 non-null       float64
 18  duration                        101227 non-null  float64
 19  foul_committed_advantage        0 non-null       float64
 20  foul_committed_card             0 non-null       float64
 21  foul_committed_penalty          0 non-null       float64
 22  foul_committed_type             0 non-null       float64
 23  foul_won_advantage              0 non-null       float64
 24  foul_won_defensive              0 non-null       float64
 25  goalkeeper_body_part            0 non-null       float64
 26  goalkeeper_end_location         0 non-null       float64
 27  goalkeeper_outcome              0 non-null       float64
 28  goalkeeper_position             0 non-null       float64
 29  goalkeeper_technique            0 non-null       float64
 30  goalkeeper_type                 0 non-null       float64
 31  id                              101227 non-null  object
 32  index                           101227 non-null  int64
 33  injury_stoppage_in_chain        0 non-null       float64
 34  interception_outcome            0 non-null       float64
 35  location                        101227 non-null  object
 36  match_id                        101227 non-null  int64
 37  minute                          101227 non-null  int64
 38  miscontrol_aerial_won           0 non-null       float64
 39  off_camera                      140 non-null     object
 40  out                             1710 non-null    object
 41  pass_aerial_won                 0 non-null       float64
 42  pass_angle                      0 non-null       float64
 43  pass_assisted_shot_id           0 non-null       float64
 44  pass_body_part                  0 non-null       float64
 45  pass_cross                      0 non-null       float64
 46  pass_cut_back                   0 non-null       float64
 47  pass_deflected                  0 non-null       float64
 48  pass_end_location               0 non-null       float64
 49  pass_height                     0 non-null       float64
 50  pass_inswinging                 0 non-null       float64
 51  pass_length                     0 non-null       float64
 52  pass_outcome                    0 non-null       float64
 53  pass_outswinging                0 non-null       float64
 54  pass_recipient                  0 non-null       float64
 55  pass_recipient_id               0 non-null       float64
 56  pass_shot_assist                0 non-null       float64
 57  pass_switch                     0 non-null       float64
 58  pass_technique                  0 non-null       float64
 59  pass_through_ball               0 non-null       float64
 60  pass_type                       0 non-null       float64
 61  period                          101227 non-null  int64
 62  play_pattern                    101227 non-null  object
 63  player                          101227 non-null  object
 64  player_id                       101227 non-null  float64
 65  position                        101227 non-null  object
 66  possession                      101227 non-null  int64
 67  possession_team                 101227 non-null  object
 68  possession_team_id              101227 non-null  int64
 69  related_events                  101227 non-null  object
 70  second                          101227 non-null  int64
 71  shot_aerial_won                 8499 non-null    object
 72  shot_body_part                  101227 non-null  object
 73  shot_end_location               101227 non-null  object
 74  shot_first_time                 31244 non-null   object
 75  shot_freeze_frame               99924 non-null   object
 76  shot_key_pass_id                70649 non-null   object
 77  shot_outcome                    101227 non-null  object
 78  shot_statsbomb_xg               101227 non-null  float64
 79  shot_technique                  101227 non-null  object
 80  shot_type                       101227 non-null  object
 81  substitution_outcome            0 non-null       float64
 82  substitution_outcome_id         0 non-null       float64
 83  substitution_replacement        0 non-null       float64
 84  substitution_replacement_id     0 non-null       float64
 85  tactics                         0 non-null       float64
 86  team                            101227 non-null  object
 87  team_id                         101227 non-null  int64
 88  timestamp                       101227 non-null  object
 89  type                            101227 non-null  object
 90  under_pressure                  24969 non-null   object
dtypes: float64(61), int64(8), object(22)
memory usage: 70.3+ MB

In [15]:
#TODO:
#Poprawić zapisywanie numer 1, bo coś (najpewniej limit zapytań do API (?)) sprawiło, że nie ma kolumny 'shot_deflected'
FILE_PATH_2 = os.path.join(GOOGLE_DRIVE_PATH, "all_statsbomb_shots_used.csv")
shots_df_used = shots_df[['period', 'position', 'location', 'play_pattern', 'under_pressure', 'shot_outcome', 'shot_type', 'shot_body_part', 'shot_technique', 'shot_first_time', 'shot_freeze_frame', 'shot_aerial_won', 'shot_statsbomb_xg']]
shots_df_used.to_csv(FILE_PATH, index=False)

In [22]:
import math
from sklearn.model_selection import train_test_split
#TODO: przepisać jako klasę
def shots_pipeline(used_dataframe=shots_df_used):

  def get_missing_data(df, axis):
    missing_rows = df.isna().sum(axis=axis)
    missing_rows_perc = np.round(missing_rows / df.shape[axis] * 100, 2)
    return missing_rows

  def process_players_postions(shot_freeze_frame, location_x, location_y):

    info = []
    count_enemies_in_shooting_range = 0
    count_non_offside_teammates = 0
    is_goal_keeper_in_shooting_range = 0
    left_post = [120, 36]
    right_post = [120, 44] # lewy i prawy słupek zgodnie ze specyfikacją stasbomb

    def calculate_triangle_area(x1, y1, x2, y2, x3, y3):
      return abs((x1 * (y2 - y3) + x2 * (y3 - y1) + x3 * (y1 - y2)) / 2.0)

    def calculate_player_triangles_area(player_x, player_y):
      area = 0

      area += calculate_triangle_area(player_x, player_y, right_post[0], right_post[1], left_post[0], left_post[1])
      area += calculate_triangle_area(player_x, player_y, left_post[0], left_post[1], location_x, location_y)
      area += calculate_triangle_area(player_x, player_y, right_post[0], right_post[1], location_x, location_y) # dałoby się ładniej napisać, można poprawić przy faktycznym pipline'ie

      return area

    def find_offside_line(shot_freeze_frame):
      offside_line = 120 # wielkosc x boiska ze specki statsbomb

      opponents_x = [
        player['location'][0]
        for player in shot_freeze_frame
        if player['teammate'] == False
      ]

      opponents_x.sort(reverse=True)
      if len(opponents_x) >= 2:
        offside_line = opponents_x[1]

      return offside_line

    shooting_triangle_area = calculate_triangle_area(location_x, location_y, right_post[0], right_post[1], left_post[0], left_post[1])
    offside_line = find_offside_line(shot_freeze_frame)

    for player in shot_freeze_frame:
      player_area = calculate_player_triangles_area(player['location'][0], player['location'][1])
      if math.isclose(player_area, shooting_triangle_area, rel_tol=0.05) and player['teammate'] == False:
        count_enemies_in_shooting_range += 1
      if (player['location'][0] <= offside_line or player['location'][0] < location_x) and player['teammate'] == True: # z zasady spalnego 2 obrońca wyznacza linie, do spalonego nie liczą się podania do tyłu
        count_non_offside_teammates += 1
      if player['position']['name'] == 'Goalkeeper' and player['teammate'] == False:
        if math.isclose(player_area, shooting_triangle_area, rel_tol=0.05):
          is_goal_keeper_in_shooting_range = 1


    info.append(count_enemies_in_shooting_range)
    info.append(count_non_offside_teammates)
    info.append(is_goal_keeper_in_shooting_range)

    return info

  def train_test_split(dataframe_to_split=used_dataframe):
    X = dataframe_to_split.drop(columns='shot_statsbomb_xg')
    y = dataframe_to_split['shot_statsbomb_xg']

    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    return X_train, X_test, y_train, y_test

  #TODO: przepisać z edy na pipeline
  def code_data(dataframe_to_code):
    dataframe_to_code_copy = dataframe_to_code.copy()

    location = dataframe_to_code_copy['location']
    x_position = []
    y_position = []
    for location in location:
      x_position.append(location[0])
      y_position.append(location[1])

    dataframe_to_code_copy.loc[:, 'location_x'] = x_position
    dataframe_to_code_copy.loc[:, 'location_y'] = y_position
    dataframe_to_code_copy = dataframe_to_code_copy.drop(columns=['location'])

    is_goal = (dataframe_to_code_copy['shot_outcome'] == 'Goal').astype(int)
    dataframe_to_code_copy.loc[:, 'is_goal'] = is_goal
    dataframe_to_code_copy = dataframe_to_code_copy.drop(columns=['shot_outcome'])

    shot_aerial_won = (dataframe_to_code_copy['shot_aerial_won'] == True).astype(int)
    shot_deflected = (dataframe_to_code_copy['shot_deflected'] == True).astype(int)
    shot_first_time = (dataframe_to_code_copy['shot_first_time'] == True).astype(int)
    under_pressure = (dataframe_to_code_copy['under_pressure'] == True).astype(int)

    dataframe_to_code_copy.loc[:, 'shot_aerial_won'] = shot_aerial_won
    dataframe_to_code_copy.loc[:, 'shot_deflected'] = shot_deflected
    dataframe_to_code_copy.loc[:, 'shot_first_time'] = shot_first_time
    dataframe_to_code_copy.loc[:, 'under_pressure'] = under_pressure


    is_goal = (dataframe_to_code['shot_outcome'] == 'Goal').astype(int)
    dataframe_to_code_copy.loc[:, 'is_goal'] = is_goal
    dataframe_to_code_copy = dataframe_to_code_copy.drop(columns=['shot_outcome'])

    return dataframe_to_code_copy

  #TODO: przepisać z edy na pipeline
  def process_shot_freeze_frame():
    processed_players_locations = []
    for freeze_frame, location_x, location_y in zip(encoded['shot_freeze_frame'], encoded['location_x'], encoded['location_y']):
      processed_players_locations.append(process_players_postions(freeze_frame, location_x, location_y))

    columns = ['enemies_in_shooting_range', 'non_offside_teammates', 'is_gk_in_shooting_range']
    encoded[columns] = pd.DataFrame(processed_players_locations, index=encoded.index)

    encoded.drop(columns=['shot_freeze_frame'], inplace=True)
    encoded

  return get_missing_data(used_dataframe, 0)

In [23]:
shots_pipeline()

period                   0
position                 0
location                 0
play_pattern             0
under_pressure       76258
shot_outcome             0
shot_type                0
shot_body_part           0
shot_technique           0
shot_first_time      69983
shot_freeze_frame     1303
shot_aerial_won      92728
shot_statsbomb_xg        0
dtype: int64