## Ważne linki (mogą przybliżyć dataset i trochę ułatwić nam zadanie):
https://www.sporthorizon.co.uk/blog/working-with-statsbomb-data-in-python
https://medium.com/@lucascarrasquillaparra/complete-guide-on-working-with-the-statsbomb-open-data-dataset-a57c26d5852b

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
!pip install statsbombpy

Collecting statsbombpy
  Downloading statsbombpy-1.22.0-py3-none-any.whl.metadata (63 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.8/63.8 kB 5.5 MB/s eta 0:00:00
Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (from statsbombpy) (2.2.3)
Requirement already satisfied: requests in /usr/local/lib/python3.13/dist-packages (from statsbombpy) (2.32.4)
Collecting requests-cache (from statsbombpy)
  Downloading requests_cache-1.3.3-py3-none-any.whl.metadata (9.4 kB)
Requirement already satisfied: inflect in /usr/local/lib/python3.13/dist-packages (from statsbombpy) (7.5.0)
Requirement already satisfied: joblib in /usr/local/lib/python3.13/dist-packages (from statsbombpy) (1.5.3)
Requirement already satisfied: more_itertools>=8.5.0 in /usr/local/lib/python3.13/dist-packages (from inflect->statsbombpy) (10.8.0)
Requirement already satisfied: typeguard>=4.0.1 in /usr/local/lib/python3.13/dist-packages (from inflect->statsbombpy) (4.6.0)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas->statsbombpy) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas->statsbombpy) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas->statsbombpy) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas->statsbombpy) (2026.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests->statsbombpy) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests->statsbombpy) (3.19)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests->statsbombpy) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests->statsbombpy) (2026.7.22)
Requirement already satisfied: attrs>=21.2 in /usr/local/lib/python3.13/dist-packages (from requests-cache->statsbombpy) (26.1.0)
Collecting cattrs>=22.2 (from requests-cache->statsbombpy)
  Downloading cattrs-26.2.0-py3-none-any.whl.metadata (8.5 kB)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests-cache->statsbombpy) (4.11.4)
Collecting url-normalize>=2.0 (from requests-cache->statsbombpy)
  Downloading url_normalize-3.0.0-py3-none-any.whl.metadata (7.5 kB)
Requirement already satisfied: typing-extensions>=4.14.0 in /usr/local/lib/python3.13/dist-packages (from cattrs>=22.2->requests-cache->statsbombpy) (4.16.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas->statsbombpy) (1.17.0)
Downloading statsbombpy-1.22.0-py3-none-any.whl (18 kB)
Downloading requests_cache-1.3.3-py3-none-any.whl (70 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 70.8/70.8 kB 3.8 MB/s eta 0:00:00
Downloading cattrs-26.2.0-py3-none-any.whl (74 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 74.8/74.8 kB 4.4 MB/s eta 0:00:00
Downloading url_normalize-3.0.0-py3-none-any.whl (16 kB)
Installing collected packages: url-normalize, cattrs, requests-cache, statsbombpy
Successfully installed cattrs-26.2.0 requests-cache-1.3.3 statsbombpy-1.22.0 url-normalize-3.0.0

In [4]:
from statsbombpy import sb
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

## "Główny" dataframe

In [5]:
comp_df = sb.competitions()

/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

In [6]:
comp_df.head(20)

,competition_id,season_id,country_name,competition_name,competition_gender,competition_youth,competition_international,season_name,match_updated,match_updated_360,match_available_360,match_available
0,9,281,Germany,1. Bundesliga,male,False,False,2023/2024,2024-09-28T20:46:38.893391,2025-11-15T23:17:41.827093,2025-11-15T23:17:41.827093,2024-09-28T20:46:38.893391
1,9,27,Germany,1. Bundesliga,male,False,False,2015/2016,2024-05-19T11:11:14.192381,None,None,2024-05-19T11:11:14.192381
2,1267,107,Africa,African Cup of Nations,male,False,True,2023,2026-05-12T21:18:08.827431,2026-05-02T02:07:18.902396,2026-05-02T02:07:18.902396,2026-05-12T21:18:08.827431
3,16,4,Europe,Champions League,male,False,False,2018/2019,2026-05-15T15:54:04.598614,2021-06-13T16:17:31.694,None,2026-05-15T15:54:04.598614
4,16,1,Europe,Champions League,male,False,False,2017/2018,2024-02-13T02:35:28.134882,2021-06-13T16:17:31.694,None,2024-02-13T02:35:28.134882
5,16,2,Europe,Champions League,male,False,False,2016/2017,2024-02-13T02:37:32.205154,2021-06-13T16:17:31.694,None,2024-02-13T02:37:32.205154
6,16,27,Europe,Champions League,male,False,False,2015/2016,2024-06-12T07:45:38.786894,2021-06-13T16:17:31.694,None,2024-06-12T07:45:38.786894
7,16,26,Europe,Champions League,male,False,False,2014/2015,2024-02-12T12:49:54.914228,2021-06-13T16:17:31.694,None,2024-02-12T12:49:54.914228
8,16,25,Europe,Champions League,male,False,False,2013/2014,2024-02-12T12:48:48.479157,2021-06-13T16:17:31.694,None,2024-02-12T12:48:48.479157
9,16,24,Europe,Champions League,male,False,False,2012/2013,2024-02-12T12:47:34.340413,2021-06-13T16:17:31.694,None,2024-02-12T12:47:34.340413
10,16,23,Europe,Champions League,male,False,False,2011/2012,2024-02-13T02:36:35.698340,2021-06-13T16:17:31.694,None,2024-02-13T02:36:35.698340
11,16,22,Europe,Champions League,male,False,False,2010/2011,2024-02-12T12:53:03.944320,2021-06-13T16:17:31.694,None,2024-02-12T12:53:03.944320
12,16,21,Europe,Champions League,male,False,False,2009/2010,2024-02-12T12:49:25.017694,2021-06-13T16:17:31.694,None,2024-02-12T12:49:25.017694
13,16,41,Europe,Champions League,male,False,False,2008/2009,2024-02-13T07:02:54.657056,2021-06-13T16:17:31.694,None,2024-02-13T07:02:54.657056
14,16,39,Europe,Champions League,male,False,False,2006/2007,2024-02-12T13:48:23.967222,2021-06-13T16:17:31.694,None,2024-02-12T13:48:23.967222
15,16,37,Europe,Champions League,male,False,False,2004/2005,2025-06-24T09:44:09.039471,2021-06-13T16:17:31.694,None,2025-06-24T09:44:09.039471
16,16,44,Europe,Champions League,male,False,False,2003/2004,2025-06-24T13:57:37.321382,2021-06-13T16:17:31.694,None,2025-06-24T13:57:37.321382
17,16,76,Europe,Champions League,male,False,False,1999/2000,2025-06-23T12:34:36.649637,2021-06-13T16:17:31.694,None,2025-06-23T12:34:36.649637
18,16,277,Europe,Champions League,male,False,False,1972/1973,2024-02-13T14:25:16.532771,None,None,2024-02-13T14:25:16.532771
19,16,71,Europe,Champions League,male,False,False,1971/1972,2024-02-12T14:25:01.735880,2021-06-13T16:17:31.694,None,2024-02-12T14:25:01.735880

In [7]:
comp_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80 entries, 0 to 79
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   competition_id             80 non-null     int64
 1   season_id                  80 non-null     int64
 2   country_name               80 non-null     object
 3   competition_name           80 non-null     object
 4   competition_gender         80 non-null     object
 5   competition_youth          80 non-null     bool
 6   competition_international  80 non-null     bool
 7   season_name                80 non-null     object
 8   match_updated              80 non-null     object
 9   match_updated_360          58 non-null     object
 10  match_available_360        12 non-null     object
 11  match_available            80 non-null     object
dtypes: bool(2), int64(2), object(8)
memory usage: 6.5+ KB

To jest "główny" df naszego datasetu, raczej w kontekscie tego co chcemy zrobić, to nie jest on jakoś bardzo istotny, przez to, że obchodzi nas głównie xG, czyli raczej eventy z konkretnego meczu - więc w sumie jedyne "ważne" dla nas kolumny to: competition_id,, season_id (i może country_name i competition_name, ale to też raczej MOŻE z dużych liter).

In [29]:
len(pd.unique(comp_df['competition_name']))

24

W darmowej wersji datasetu mamy dostęp do danych z 24 różnych rozgrywek, z czego np.

In [53]:
print("-" ,len(pd.unique(comp_df['season_name'][comp_df['competition_name'] == 'Champions League'])), "sezonów w Lidze Mistrzów")
print("-" ,len(pd.unique(comp_df['season_name'][comp_df['competition_name'] == '1. Bundesliga'])), "sezony w Bundeslidze")
print("-" ,len(pd.unique(comp_df['season_name'][comp_df['competition_name'] == 'La Liga'])), "sezonów w La Lidze")

- 18 sezonów w Lidze Mistrzów
- 2 sezony w Bundeslidze
- 18 sezonów w La Lidze

In [68]:
comp_df[comp_df['competition_name'] == 'La Liga'].head(5) # przykładowo, choć dalej będzie przykład bundesligowy

,competition_id,season_id,country_name,competition_name,competition_gender,competition_youth,competition_international,season_name,match_updated,match_updated_360,match_available_360,match_available
40,11,90,Spain,La Liga,male,False,False,2020/2021,2025-11-02T03:55:19.577958,2025-11-02T03:55:53.923193,2025-11-02T03:55:53.923193,2025-11-02T03:55:19.577958
41,11,42,Spain,La Liga,male,False,False,2019/2020,2024-12-16T16:51:06.833054,2021-06-13T16:17:31.694,None,2024-12-16T16:51:06.833054
42,11,4,Spain,La Liga,male,False,False,2018/2019,2026-04-06T04:49:09.959011,2021-07-09T14:53:22.103024,None,2026-04-06T04:49:09.959011
43,11,1,Spain,La Liga,male,False,False,2017/2018,2025-07-14T10:01:16.674864,2021-06-13T16:17:31.694,None,2025-07-14T10:01:16.674864
44,11,2,Spain,La Liga,male,False,False,2016/2017,2025-03-09T16:03:54.962718,2021-06-13T16:17:31.694,None,2025-03-09T16:03:54.962718

In [76]:
comp_df['competition_name'].mode()

0    Champions League
1             La Liga
Name: competition_name, dtype: object

Najliczniej w datasecie występują dane z Champions League i La Liga.

## Coraz bliżej naszego "mięsa"

In [10]:
matches_presentation_df = sb.matches(competition_id=9, season_id=27) # wybór meczów z danych rozgrywek i danego sezonu

/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

In [9]:
matches_presentation_df.head(20)

,match_id,match_date,kick_off,home_score,away_score,match_status,match_status_360,last_updated,last_updated_360,match_week,...,home_manager_country_name,away_manager_id,away_manager_name,away_manager_nickname,away_manager_dob,away_manager_country_id,away_manager_country_name,data_version,shot_fidelity_version,xy_fidelity_version
0,3890563,2016-05-14,15:30:00.000,3,2,available,unscheduled,2023-08-05T09:38:01.494282,None,34,...,Germany,44,Ralph Hasenhüttl,None,1967-08-09,15,Austria,1.1.0,2,2
1,3890550,2016-05-07,15:30:00.000,2,1,available,unscheduled,2023-10-28T23:30:33.200742,None,33,...,Germany,3980,Roger Schmidt,None,1967-03-13,85,Germany,1.1.0,2,2
2,3890540,2016-04-30,18:30:00.000,2,1,available,unscheduled,2023-07-24T07:41:44.627113,None,32,...,Germany,51,Pál Dárdai,None,1976-03-16,103,Hungary,1.1.0,2,2
3,3890534,2016-04-23,18:30:00.000,2,3,available,unscheduled,2023-07-19T17:07:48.502966,None,31,...,Germany,3980,Roger Schmidt,None,1967-03-13,85,Germany,1.1.0,2,2
4,3890521,2016-04-16,15:30:00.000,3,0,available,unscheduled,2023-07-25T09:12:32.507875,None,30,...,Germany,374,Niko Kovač,None,1971-10-15,56,Croatia,1.1.0,2,2
5,3890519,2016-04-10,17:30:00.000,0,2,available,unscheduled,2023-07-31T12:19:56.474040,None,29,...,Austria,3980,Roger Schmidt,None,1967-03-13,85,Germany,1.1.0,2,2
6,3890502,2016-04-01,20:30:00.000,3,0,available,unscheduled,2023-08-03T13:07:07.427967,None,28,...,Germany,411,Dieter Hecking,None,1964-09-12,85,Germany,1.1.0,2,2
7,3890500,2016-03-20,16:30:00.000,0,2,available,unscheduled,2023-07-19T13:10:23.962185,None,27,...,Germany,3980,Roger Schmidt,None,1967-03-13,85,Germany,1.1.0,2,2
8,3890492,2016-03-13,16:30:00.000,1,0,available,unscheduled,2023-08-03T13:06:19.003897,None,26,...,Germany,446,Bruno Labbadia,None,1966-02-08,85,Germany,1.1.0,2,2
9,3890477,2016-03-05,16:30:00.000,3,3,available,unscheduled,2023-07-24T09:18:59.971988,None,25,...,Germany,3980,Roger Schmidt,None,1967-03-13,85,Germany,1.1.0,2,2
10,3890472,2016-03-02,21:00:00.000,1,4,available,unscheduled,2023-07-18T12:42:28.657695,None,24,...,Germany,3055,Viktor Skripnik,None,1969-11-19,238,Ukraine,1.1.0,2,2
11,3890463,2016-02-28,18:30:00.000,3,1,available,unscheduled,2023-12-12T01:48:54.981843,None,23,...,Switzerland,1002246,Markus Krösche,None,1980-09-17,85,Germany,1.1.0,2,2
12,3890456,2016-02-21,16:30:00.000,0,1,available,unscheduled,2023-07-15T21:48:00.266005,None,22,...,Germany,279,Thomas Tuchel,None,1973-08-29,85,Germany,1.1.0,2,2
13,3890444,2016-02-13,16:30:00.000,1,2,available,unscheduled,2023-07-15T16:09:34.211127,None,21,...,Germany,3980,Roger Schmidt,None,1967-03-13,85,Germany,1.1.0,2,2
14,3890431,2016-02-06,19:30:00.000,0,0,available,unscheduled,2023-07-12T18:20:28.803251,None,20,...,Germany,36,Josep Guardiola i Sala,Pep Guardiola,1971-01-18,214,Spain,1.1.0,2,2
15,3890427,2016-01-30,16:30:00.000,3,0,available,unscheduled,2023-08-03T13:03:43.290703,None,19,...,Germany,6065,Thomas Schaaf,None,1961-04-30,85,Germany,1.1.0,2,2
16,3890415,2016-01-23,16:30:00.000,1,1,available,unscheduled,2023-07-13T09:28:13.556051,None,18,...,Netherlands,3980,Roger Schmidt,None,1967-03-13,85,Germany,1.1.0,2,2
17,3890409,2015-12-19,16:30:00.000,0,1,available,unscheduled,2023-08-03T13:02:05.091113,None,17,...,Austria,3980,Roger Schmidt,None,1967-03-13,85,Germany,1.1.0,2,2
18,3890395,2015-12-12,19:30:00.000,5,0,available,unscheduled,2023-07-16T22:31:14.141541,None,16,...,Germany,3650,André Schubert,None,1971-07-24,85,Germany,1.1.0,2,2
19,3890390,2015-12-05,16:30:00.000,2,1,available,unscheduled,2023-07-18T05:53:50.179730,None,15,...,Hungary,3980,Roger Schmidt,None,1967-03-13,85,Germany,1.1.0,2,2

Tutaj ponownie nie ma zbyt dużo przydatnych dla nas informacji (chyba, że będziemy chcieli też iść w predykcje biorąc pod uwage menadżera (?), bo jednak to też ma jakieś znaczenie - styl ofensywny vs defensywny).

Tu ważne dla nas na 100% jest match_id, bo możemy sobie wybrać eventy podczas tego meczu - czyli no wszystkie zdarzenia, co w kontekście naszego projektu jest jak foliowa czapeczka dla wujka, bez niej nie ruszy się na działke, tak jak my nie mamy po co zaczynać tematu.

In [66]:
len(pd.unique(matches_presentation_df['match_id']))

34

Przykładowo w tym sezonie Bundesligi mamy aż 34 mecze, co sprawia, że danych będziemy mieli w chuj i jeszcze trochę XD

## Creme de la creme - czyli to co jest dla nas ważne

In [11]:
concrete_match_df = sb.events(match_id=3890563) # wybór konkretnego meczu

/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

In [12]:
concrete_match_df.head(20)

,50_50,ball_receipt_outcome,ball_recovery_recovery_failure,block_deflection,block_offensive,block_save_block,carry_end_location,clearance_aerial_won,clearance_body_part,clearance_head,...,substitution_outcome,substitution_outcome_id,substitution_replacement,substitution_replacement_id,tactics,team,team_id,timestamp,type,under_pressure
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,"{'formation': 442, 'lineup': [{'player': {'id'...",Bayer Leverkusen,904,00:00:00.000,Starting XI,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,"{'formation': 433, 'lineup': [{'player': {'id'...",Ingolstadt,189,00:00:00.000,Starting XI,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Bayer Leverkusen,904,00:00:00.000,Half Start,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Ingolstadt,189,00:00:00.000,Half Start,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Bayer Leverkusen,904,00:00:00.000,Half Start,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Ingolstadt,189,00:00:00.000,Half Start,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Bayer Leverkusen,904,00:00:00.700,Pass,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Bayer Leverkusen,904,00:00:02.489,Pass,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Bayer Leverkusen,904,00:00:04.532,Pass,True
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Bayer Leverkusen,904,00:00:06.781,Pass,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Bayer Leverkusen,904,00:00:09.572,Pass,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Bayer Leverkusen,904,00:00:11.444,Pass,NaN
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Ingolstadt,189,00:00:26.251,Pass,NaN
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Bayer Leverkusen,904,00:00:35.755,Pass,NaN
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Bayer Leverkusen,904,00:00:36.656,Pass,NaN
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Bayer Leverkusen,904,00:00:46.437,Pass,NaN
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Bayer Leverkusen,904,00:00:48.034,Pass,True
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Bayer Leverkusen,904,00:00:49.252,Pass,NaN
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Ingolstadt,189,00:01:01.389,Pass,NaN
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Ingolstadt,189,00:01:02.122,Pass,True

In [13]:
concrete_match_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2975 entries, 0 to 2974
Data columns (total 94 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   50_50                           4 non-null      object
 1   ball_receipt_outcome            139 non-null    object
 2   ball_recovery_recovery_failure  8 non-null      object
 3   block_deflection                2 non-null      object
 4   block_offensive                 2 non-null      object
 5   block_save_block                2 non-null      object
 6   carry_end_location              537 non-null    object
 7   clearance_aerial_won            11 non-null     object
 8   clearance_body_part             46 non-null     object
 9   clearance_head                  25 non-null     object
 10  clearance_left_foot             8 non-null      object
 11  clearance_right_foot            13 non-null     object
 12  counterpress                    152 non-null    object
 13  dribble_nutmeg                  4 non-null      object
 14  dribble_outcome                 40 non-null     object
 15  dribble_overrun                 2 non-null      object
 16  duel_outcome                    41 non-null     object
 17  duel_type                       97 non-null     object
 18  duration                        2309 non-null   float64
 19  foul_committed_advantage        5 non-null      object
 20  foul_committed_card             2 non-null      object
 21  foul_committed_penalty          1 non-null      object
 22  foul_committed_type             2 non-null      object
 23  foul_won_advantage              5 non-null      object
 24  foul_won_defensive              6 non-null      object
 25  foul_won_penalty                1 non-null      object
 26  goalkeeper_body_part            6 non-null      object
 27  goalkeeper_end_location         22 non-null     object
 28  goalkeeper_outcome              15 non-null     object
 29  goalkeeper_position             31 non-null     object
 30  goalkeeper_technique            9 non-null      object
 31  goalkeeper_type                 37 non-null     object
 32  id                              2975 non-null   object
 33  index                           2975 non-null   int64
 34  injury_stoppage_in_chain        1 non-null      object
 35  interception_outcome            35 non-null     object
 36  location                        2945 non-null   object
 37  match_id                        2975 non-null   int64
 38  minute                          2975 non-null   int64
 39  miscontrol_aerial_won           3 non-null      object
 40  off_camera                      60 non-null     object
 41  out                             38 non-null     object
 42  pass_aerial_won                 41 non-null     object
 43  pass_angle                      783 non-null    float64
 44  pass_assisted_shot_id           19 non-null     object
 45  pass_body_part                  683 non-null    object
 46  pass_cross                      17 non-null     object
 47  pass_deflected                  1 non-null      object
 48  pass_end_location               783 non-null    object
 49  pass_goal_assist                4 non-null      object
 50  pass_height                     783 non-null    object
 51  pass_length                     783 non-null    float64
 52  pass_miscommunication           1 non-null      object
 53  pass_outcome                    255 non-null    object
 54  pass_outswinging                6 non-null      object
 55  pass_recipient                  667 non-null    object
 56  pass_recipient_id               667 non-null    float64
 57  pass_shot_assist                15 non-null     object
 58  pass_switch                     19 non-null     object
 59  pass_technique                  13 non-null     object
 60  pass_through_ball               7 non-null      object
 61  pass_type                       249 non-null    object
 62  period                          2975 non-null   int64
 63  play_pattern                    2975 non-null   object
 64  player                          2959 non-null   object
 65  player_id                       2959 non-null   float64
 66  position                        2959 non-null   object
 67  possession                      2975 non-null   int64
 68  possession_team                 2975 non-null   object
 69  possession_team_id              2975 non-null   int64
 70  related_events                  2826 non-null   object
 71  second                          2975 non-null   int64
 72  shot_aerial_won                 1 non-null      object
 73  shot_body_part                  31 non-null     object
 74  shot_end_location               31 non-null     object
 75  shot_first_time                 17 non-null     object
 76  shot_freeze_frame               30 non-null     object
 77  shot_key_pass_id                19 non-null     object
 78  shot_one_on_one                 3 non-null      object
 79  shot_open_goal                  3 non-null      object
 80  shot_outcome                    31 non-null     object
 81  shot_statsbomb_xg               31 non-null     float64
 82  shot_technique                  31 non-null     object
 83  shot_type                       31 non-null     object
 84  substitution_outcome            6 non-null      object
 85  substitution_outcome_id         6 non-null      float64
 86  substitution_replacement        6 non-null      object
 87  substitution_replacement_id     6 non-null      float64
 88  tactics                         5 non-null      object
 89  team                            2975 non-null   object
 90  team_id                         2975 non-null   int64
 91  timestamp                       2975 non-null   object
 92  type                            2975 non-null   object
 93  under_pressure                  823 non-null    object
dtypes: float64(8), int64(8), object(78)
memory usage: 2.1+ MB

Dla każdego meczu mamy dużo dużo danych różnego typu, tu  przy edzie  będzie trzeba przekminić, które z tych kolumn będą dla nas ważne, a które to "śmieci", bo tutaj mamy każdą akcję z meczu.

In [16]:
shots_df = concrete_match_df[concrete_match_df['type'] == 'Shot']

In [20]:
shots_df[['player', 'team', 'shot_statsbomb_xg', 'shot_outcome']]

,player,team,shot_statsbomb_xg,shot_outcome
2880,Moritz Hartmann,Ingolstadt,0.008072,Off T
2881,Pascal Groß,Ingolstadt,0.046675,Blocked
2882,Mathew Leckie,Ingolstadt,0.097066,Off T
2883,Mathew Leckie,Ingolstadt,0.977242,Goal
2884,Moritz Hartmann,Ingolstadt,0.267620,Off T
2885,Benjamin Hübner,Ingolstadt,0.029614,Off T
2886,Danny Vieira da Costa,Ingolstadt,0.018916,Wayward
2887,Charles Mariano Aránguiz Sandoval,Bayer Leverkusen,0.365020,Goal
2888,Kevin Kampl,Bayer Leverkusen,0.439847,Goal
2889,Moritz Hartmann,Ingolstadt,0.006357,Saved
2890,Markus Suttner,Ingolstadt,0.011275,Off T
2891,Karim Bellarabi,Bayer Leverkusen,0.775621,Wayward
2892,Almog Cohen,Ingolstadt,0.123469,Blocked
2893,Stefan Kießling,Bayer Leverkusen,0.936730,Goal
2894,Moritz Hartmann,Ingolstadt,0.783500,Goal
2895,Moritz Hartmann,Ingolstadt,0.025636,Post
2896,Moritz Hartmann,Ingolstadt,0.093112,Saved
2897,Dario Lezcano,Ingolstadt,0.355952,Off T
2898,Moritz Hartmann,Ingolstadt,0.025735,Wayward
2899,Dario Lezcano,Ingolstadt,0.119046,Blocked
2900,Max Christiansen,Ingolstadt,0.046375,Off T
2901,Karim Bellarabi,Bayer Leverkusen,0.602505,Blocked
2902,Karim Bellarabi,Bayer Leverkusen,0.046221,Blocked
2903,Hakan Çalhanoğlu,Bayer Leverkusen,0.006680,Off T
2904,Julian Brandt,Bayer Leverkusen,0.127539,Saved
2905,Admir Mehmedi,Bayer Leverkusen,0.070582,Wayward
2906,Karim Bellarabi,Bayer Leverkusen,0.125832,Saved
2907,Markus Suttner,Ingolstadt,0.015990,Off T
2908,Marvin Matip,Ingolstadt,0.088643,Off T
2909,Max Christiansen,Ingolstadt,0.040934,Wayward
2910,Markus Suttner,Ingolstadt,0.060580,Off T

In [25]:
print(len(shots_df))
print(len(shots_df[shots_df['team'] == 'Bayer Leverkusen']))
print(len(shots_df[shots_df['team'] == 'Ingolstadt']))

31
10
21

I tu nagle (co raczej spodziewane) okazuje się, że nie ma milionów strzałów, tylko, że łacznie było ich 31, z czego 10 dla Leverkusen, a 21 dla Ingolstadt.

## Ciekawostkowe rzeczy

Z ciekawych funkcji (choć raczej też nie jakoś bardzo przdyatnych dla nas) można sobie też wyświetlić lineup w danym meczu

In [54]:
def print_lineups(match_id, team1, team2):
  print(f"Lineup {team1}", sb.lineups(match_id=match_id)[team1])
  print(f"Lineup {team2}", sb.lineups(match_id=match_id)[team1])

In [55]:
print_lineups(match_id=3890563, team1='Bayer Leverkusen', team2='Ingolstadt')

/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Lineup Bayer Leverkusen     player_id                        player_name   player_nickname  \
0        5555                      Julian Brandt              None
1        7039                   Hakan Çalhanoğlu              None
2        8210  Charles Mariano Aránguiz Sandoval  Charles Aránguiz
3        8211                  Benjamin Henrichs              None
4        8213                    Karim Bellarabi              None
5        8219                      Admir Mehmedi              None
6        8222                        Kevin Kampl              None
7        8573                        Ömer Toprak              None
8        8918                    Roberto Hilbert              None
9        9363                André Ramalho Silva     André Ramalho
10       9892                       Lukas Boeder              None
11      11394                    Stefan Kießling              None
12      15581                         Bernd Leno              None
13      20415                 Sebastian Boenisch              None
14      21168                        Marlon Frey              None
15     400627                       Dario Kresic              None
16     401501                     David Yelldell              None

    jersey_number                   country  \
0              19                   Germany
1              10                    Turkey
2              20                     Chile
3              39                   Germany
4              38                   Germany
5              14               Switzerland
6              44                  Slovenia
7              21                    Turkey
8              13                   Germany
9               2                    Brazil
10             33                   Germany
11             11                   Germany
12              1                   Germany
13             17                    Poland
14             37                   Germany
15             25                   Croatia
16             22  United States of America

                                                cards  \
0                                                  []
1                                                  []
2                                                  []
3   [{'time': '71:43', 'card_type': 'Yellow Card',...
4                                                  []
5                                                  []
6                                                  []
7                                                  []
8                                                  []
9                                                  []
10                                                 []
11                                                 []
12                                                 []
13                                                 []
14                                                 []
15                                                 []
16                                                 []

                                            positions
0   [{'position_id': 16, 'position': 'Left Midfiel...
1   [{'position_id': 24, 'position': 'Left Center ...
2   [{'position_id': 9, 'position': 'Right Defensi...
3   [{'position_id': 6, 'position': 'Left Back', '...
4   [{'position_id': 12, 'position': 'Right Midfie...
5   [{'position_id': 22, 'position': 'Right Center...
6   [{'position_id': 11, 'position': 'Left Defensi...
7   [{'position_id': 5, 'position': 'Left Center B...
8   [{'position_id': 2, 'position': 'Right Back', ...
9   [{'position_id': 3, 'position': 'Right Center ...
10                                                 []
11  [{'position_id': 22, 'position': 'Right Center...
12                                                 []
13                                                 []
14  [{'position_id': 2, 'position': 'Right Back', ...
15  [{'position_id': 1, 'position': 'Goalkeeper', ...
16  [{'position_id': 1, 'position': 'Goalkeeper', ...
Lineup Ingolstadt     player_id                        player_name   player_nickname  \
0        5555                      Julian Brandt              None
1        7039                   Hakan Çalhanoğlu              None
2        8210  Charles Mariano Aránguiz Sandoval  Charles Aránguiz
3        8211                  Benjamin Henrichs              None
4        8213                    Karim Bellarabi              None
5        8219                      Admir Mehmedi              None
6        8222                        Kevin Kampl              None
7        8573                        Ömer Toprak              None
8        8918                    Roberto Hilbert              None
9        9363                André Ramalho Silva     André Ramalho
10       9892                       Lukas Boeder              None
11      11394                    Stefan Kießling              None
12      15581                         Bernd Leno              None
13      20415                 Sebastian Boenisch              None
14      21168                        Marlon Frey              None
15     400627                       Dario Kresic              None
16     401501                     David Yelldell              None

    jersey_number                   country  \
0              19                   Germany
1              10                    Turkey
2              20                     Chile
3              39                   Germany
4              38                   Germany
5              14               Switzerland
6              44                  Slovenia
7              21                    Turkey
8              13                   Germany
9               2                    Brazil
10             33                   Germany
11             11                   Germany
12              1                   Germany
13             17                    Poland
14             37                   Germany
15             25                   Croatia
16             22  United States of America

                                                cards  \
0                                                  []
1                                                  []
2                                                  []
3   [{'time': '71:43', 'card_type': 'Yellow Card',...
4                                                  []
5                                                  []
6                                                  []
7                                                  []
8                                                  []
9                                                  []
10                                                 []
11                                                 []
12                                                 []
13                                                 []
14                                                 []
15                                                 []
16                                                 []

                                            positions
0   [{'position_id': 16, 'position': 'Left Midfiel...
1   [{'position_id': 24, 'position': 'Left Center ...
2   [{'position_id': 9, 'position': 'Right Defensi...
3   [{'position_id': 6, 'position': 'Left Back', '...
4   [{'position_id': 12, 'position': 'Right Midfie...
5   [{'position_id': 22, 'position': 'Right Center...
6   [{'position_id': 11, 'position': 'Left Defensi...
7   [{'position_id': 5, 'position': 'Left Center B...
8   [{'position_id': 2, 'position': 'Right Back', ...
9   [{'position_id': 3, 'position': 'Right Center ...
10                                                 []
11  [{'position_id': 22, 'position': 'Right Center...
12                                                 []
13                                                 []
14  [{'position_id': 2, 'position': 'Right Back', ...
15  [{'position_id': 1, 'position': 'Goalkeeper', ...
16  [{'position_id': 1, 'position': 'Goalkeeper', ...

/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

## *Wybór meczu przypadkowy, Bundesliga mi jeszcze nie zapłaciła.