In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
!pip install statsbombpy

Collecting statsbombpy
  Downloading statsbombpy-1.22.0-py3-none-any.whl.metadata (63 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.8/63.8 kB 2.5 MB/s eta 0:00:00
Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (from statsbombpy) (2.2.3)
Requirement already satisfied: requests in /usr/local/lib/python3.13/dist-packages (from statsbombpy) (2.32.4)
Collecting requests-cache (from statsbombpy)
  Downloading requests_cache-1.3.3-py3-none-any.whl.metadata (9.4 kB)
Requirement already satisfied: inflect in /usr/local/lib/python3.13/dist-packages (from statsbombpy) (7.5.0)
Requirement already satisfied: joblib in /usr/local/lib/python3.13/dist-packages (from statsbombpy) (1.5.3)
Requirement already satisfied: more_itertools>=8.5.0 in /usr/local/lib/python3.13/dist-packages (from inflect->statsbombpy) (10.8.0)
Requirement already satisfied: typeguard>=4.0.1 in /usr/local/lib/python3.13/dist-packages (from inflect->statsbombpy) (4.6.0)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas->statsbombpy) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas->statsbombpy) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas->statsbombpy) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas->statsbombpy) (2026.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests->statsbombpy) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests->statsbombpy) (3.19)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests->statsbombpy) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests->statsbombpy) (2026.7.22)
Requirement already satisfied: attrs>=21.2 in /usr/local/lib/python3.13/dist-packages (from requests-cache->statsbombpy) (26.1.0)
Collecting cattrs>=22.2 (from requests-cache->statsbombpy)
  Downloading cattrs-26.1.0-py3-none-any.whl.metadata (8.5 kB)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests-cache->statsbombpy) (4.11.4)
Collecting url-normalize>=2.0 (from requests-cache->statsbombpy)
  Downloading url_normalize-3.0.0-py3-none-any.whl.metadata (7.5 kB)
Requirement already satisfied: typing-extensions>=4.14.0 in /usr/local/lib/python3.13/dist-packages (from cattrs>=22.2->requests-cache->statsbombpy) (4.16.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas->statsbombpy) (1.17.0)
Downloading statsbombpy-1.22.0-py3-none-any.whl (18 kB)
Downloading requests_cache-1.3.3-py3-none-any.whl (70 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 70.8/70.8 kB 4.5 MB/s eta 0:00:00
Downloading cattrs-26.1.0-py3-none-any.whl (73 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.1/73.1 kB 6.6 MB/s eta 0:00:00
Downloading url_normalize-3.0.0-py3-none-any.whl (16 kB)
Installing collected packages: url-normalize, cattrs, requests-cache, statsbombpy
Successfully installed cattrs-26.1.0 requests-cache-1.3.3 statsbombpy-1.22.0 url-normalize-3.0.0

###Jest to moje podejście pod analizę danych piłkarskich ze Stats Bomb Open Data

In [ ]:
from statsbombpy import sb
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
sb.competitions()

/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

,competition_id,season_id,country_name,competition_name,competition_gender,competition_youth,competition_international,season_name,match_updated,match_updated_360,match_available_360,match_available
0,9,281,Germany,1. Bundesliga,male,False,False,2023/2024,2024-09-28T20:46:38.893391,2025-11-15T23:17:41.827093,2025-11-15T23:17:41.827093,2024-09-28T20:46:38.893391
1,9,27,Germany,1. Bundesliga,male,False,False,2015/2016,2024-05-19T11:11:14.192381,None,None,2024-05-19T11:11:14.192381
2,1267,107,Africa,African Cup of Nations,male,False,True,2023,2026-05-12T21:18:08.827431,2026-05-02T02:07:18.902396,2026-05-02T02:07:18.902396,2026-05-12T21:18:08.827431
3,16,4,Europe,Champions League,male,False,False,2018/2019,2026-05-15T15:54:04.598614,2021-06-13T16:17:31.694,None,2026-05-15T15:54:04.598614
4,16,1,Europe,Champions League,male,False,False,2017/2018,2024-02-13T02:35:28.134882,2021-06-13T16:17:31.694,None,2024-02-13T02:35:28.134882
...,...,...,...,...,...,...,...,...,...,...,...,...
75,35,75,Europe,UEFA Europa League,male,False,False,1988/1989,2026-04-11T12:48:10.012987,2021-06-13T16:17:31.694,None,2026-04-11T12:48:10.012987
76,53,315,Europe,UEFA Women's Euro,female,False,True,2025,2026-04-27T22:02:42.690507,2026-04-27T22:03:28.087062,2026-04-27T22:03:28.087062,2026-04-27T22:02:42.690507
77,53,106,Europe,UEFA Women's Euro,female,False,True,2022,2026-05-05T03:03:04.199896,2026-05-05T03:05:32.480837,2026-05-05T03:05:32.480837,2026-05-05T03:03:04.199896
78,72,107,International,Women's World Cup,female,False,True,2023,2026-05-03T13:51:31.021141,2026-05-03T13:55:52.303219,2026-05-03T13:55:52.303219,2026-05-03T13:51:31.021141
79,72,30,International,Women's World Cup,female,False,True,2019,2026-05-15T15:31:40.299642,2021-06-13T16:17:31.694,None,2026-05-15T15:31:40.299642

In [ ]:
sb.competitions().info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80 entries, 0 to 79
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   competition_id             80 non-null     int64
 1   season_id                  80 non-null     int64
 2   country_name               80 non-null     object
 3   competition_name           80 non-null     object
 4   competition_gender         80 non-null     object
 5   competition_youth          80 non-null     bool
 6   competition_international  80 non-null     bool
 7   season_name                80 non-null     object
 8   match_updated              80 non-null     object
 9   match_updated_360          58 non-null     object
 10  match_available_360        12 non-null     object
 11  match_available            80 non-null     object
dtypes: bool(2), int64(2), object(8)
memory usage: 6.5+ KB

/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

In [ ]:
sb.matches(competition_id=9, season_id=27).head()

/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

,match_id,match_date,kick_off,home_score,away_score,match_status,match_status_360,last_updated,last_updated_360,match_week,...,home_manager_country_name,away_manager_id,away_manager_name,away_manager_nickname,away_manager_dob,away_manager_country_id,away_manager_country_name,data_version,shot_fidelity_version,xy_fidelity_version
0,3890563,2016-05-14,15:30:00.000,3,2,available,unscheduled,2023-08-05T09:38:01.494282,None,34,...,Germany,44,Ralph Hasenhüttl,None,1967-08-09,15,Austria,1.1.0,2,2
1,3890550,2016-05-07,15:30:00.000,2,1,available,unscheduled,2023-10-28T23:30:33.200742,None,33,...,Germany,3980,Roger Schmidt,None,1967-03-13,85,Germany,1.1.0,2,2
2,3890540,2016-04-30,18:30:00.000,2,1,available,unscheduled,2023-07-24T07:41:44.627113,None,32,...,Germany,51,Pál Dárdai,None,1976-03-16,103,Hungary,1.1.0,2,2
3,3890534,2016-04-23,18:30:00.000,2,3,available,unscheduled,2023-07-19T17:07:48.502966,None,31,...,Germany,3980,Roger Schmidt,None,1967-03-13,85,Germany,1.1.0,2,2
4,3890521,2016-04-16,15:30:00.000,3,0,available,unscheduled,2023-07-25T09:12:32.507875,None,30,...,Germany,374,Niko Kovač,None,1971-10-15,56,Croatia,1.1.0,2,2

In [ ]:
def print_lineups(match_id, team1, team2):
  lineup1 = sb.lineups(match_id=match_id)[team1]
  lineup2 = sb.lineups(match_id=match_id)[team2]
  print(f"Lineup {team1}")
  print(lineup1)
  print(f"Lineup {team2}")
  print(lineup2)

In [ ]:
print_lineups(match_id=3890563, team1='Bayer Leverkusen', team2='Ingolstadt')

Lineup Bayer Leverkusen
    player_id                        player_name   player_nickname  \
0        5555                      Julian Brandt              None
1        7039                   Hakan Çalhanoğlu              None
2        8210  Charles Mariano Aránguiz Sandoval  Charles Aránguiz
3        8211                  Benjamin Henrichs              None
4        8213                    Karim Bellarabi              None
5        8219                      Admir Mehmedi              None
6        8222                        Kevin Kampl              None
7        8573                        Ömer Toprak              None
8        8918                    Roberto Hilbert              None
9        9363                André Ramalho Silva     André Ramalho
10       9892                       Lukas Boeder              None
11      11394                    Stefan Kießling              None
12      15581                         Bernd Leno              None
13      20415                 Sebastian Boenisch              None
14      21168                        Marlon Frey              None
15     400627                       Dario Kresic              None
16     401501                     David Yelldell              None

    jersey_number                   country  \
0              19                   Germany
1              10                    Turkey
2              20                     Chile
3              39                   Germany
4              38                   Germany
5              14               Switzerland
6              44                  Slovenia
7              21                    Turkey
8              13                   Germany
9               2                    Brazil
10             33                   Germany
11             11                   Germany
12              1                   Germany
13             17                    Poland
14             37                   Germany
15             25                   Croatia
16             22  United States of America

                                                cards  \
0                                                  []
1                                                  []
2                                                  []
3   [{'time': '71:43', 'card_type': 'Yellow Card',...
4                                                  []
5                                                  []
6                                                  []
7                                                  []
8                                                  []
9                                                  []
10                                                 []
11                                                 []
12                                                 []
13                                                 []
14                                                 []
15                                                 []
16                                                 []

                                            positions
0   [{'position_id': 16, 'position': 'Left Midfiel...
1   [{'position_id': 24, 'position': 'Left Center ...
2   [{'position_id': 9, 'position': 'Right Defensi...
3   [{'position_id': 6, 'position': 'Left Back', '...
4   [{'position_id': 12, 'position': 'Right Midfie...
5   [{'position_id': 22, 'position': 'Right Center...
6   [{'position_id': 11, 'position': 'Left Defensi...
7   [{'position_id': 5, 'position': 'Left Center B...
8   [{'position_id': 2, 'position': 'Right Back', ...
9   [{'position_id': 3, 'position': 'Right Center ...
10                                                 []
11  [{'position_id': 22, 'position': 'Right Center...
12                                                 []
13                                                 []
14  [{'position_id': 2, 'position': 'Right Back', ...
15  [{'position_id': 1, 'position': 'Goalkeeper', ...
16  [{'position_id': 1, 'position': 'Goalkeeper', ...
Lineup Ingolstadt
    player_id            player_name player_nickname  jersey_number  \
0        3097            Pascal Groß            None             10
1        3221         Markus Suttner            None             29
2        5481          Mathew Leckie            None              7
3        8394           Robert Bauer            None             23
4        8405        Benjamin Hübner            None              5
5        8676  Danny Vieira da Costa  Danny da Costa             21
6        9103       Lukas Hinterseer            None             16
7        9106           Marvin Matip            None             34
8        9113          Dario Lezcano   Darío Lezcano             37
9       10483  Ørjan Håskjold Nyland    Ørjan Nyland             26
10      12304        Alfredo Morales            None              6
11      12319          Ramazan Özcan            None              1
12      12551       Max Christiansen            None             19
13      13332        Romain Brégerie            None             18
14      20485            Almog Cohen            None             36
15      40460          Tobias Levels            None             28
16      40463             Stefan Lex            None             14
17      40464        Moritz Hartmann            None              9

                     country  \
0                    Germany
1                    Austria
2                  Australia
3                    Germany
4                    Germany
5                    Germany
6                    Austria
7                   Cameroon
8                   Paraguay
9                     Norway
10  United States of America
11                   Austria
12                   Germany
13                    France
14                    Israel
15                   Germany
16                   Germany
17                   Germany

                                                cards  \
0                                                  []
1                                                  []
2                                                  []
3                                                  []
4                                                  []
5                                                  []
6                                                  []
7                                                  []
8                                                  []
9                                                  []
10                                                 []
11                                                 []
12  [{'time': '79:39', 'card_type': 'Yellow Card',...
13                                                 []
14                                                 []
15                                                 []
16                                                 []
17                                                 []

                                            positions
0   [{'position_id': 13, 'position': 'Right Center...
1   [{'position_id': 6, 'position': 'Left Back', '...
2   [{'position_id': 21, 'position': 'Left Wing', ...
3   [{'position_id': 10, 'position': 'Center Defen...
4   [{'position_id': 5, 'position': 'Left Center B...
5   [{'position_id': 2, 'position': 'Right Back', ...
6   [{'position_id': 21, 'position': 'Left Wing', ...
7   [{'position_id': 3, 'position': 'Right Center ...
8   [{'position_id': 23, 'position': 'Center Forwa...
9   [{'position_id': 1, 'position': 'Goalkeeper', ...
10                                                 []
11                                                 []
12  [{'position_id': 10, 'position': 'Center Defen...
13                                                 []
14  [{'position_id': 15, 'position': 'Left Center ...
15                                                 []
16  [{'position_id': 10, 'position': 'Center Defen...
17  [{'position_id': 17, 'position': 'Right Wing',...

/usr/local/lib/python3.13/dist-packages/statsbombpy/api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

In [ ]:
def comeptitions_analysis():
  df_competitons = sb.competitions()

  print(f"Total entries: {len(df_competitons)}")
  print(f"Unique competitions: {len(df_competitons["competition_name"].unique())}")
  print(f"Unique seasons: {len(df_competitons['season_name'].unique())}")
  print(f"Countires: {len(df_competitons['country_name'].unique())}")
  print(f"Entries from bundesliga: {len(df_competitons[df_competitons['competition_name'] == '1. Bundesliga'])}")
  print(f"Competition with most entries: {df_competitons[df_competitons['competition_name'].max()]}")

In [ ]:
df_competitons = sb.competitions()
df_competitons[df_competitons['competition_name'] == "Women's World Cup"]

,competition_id,season_id,country_name,competition_name,competition_gender,competition_youth,competition_international,season_name,match_updated,match_updated_360,match_available_360,match_available
78,72,107,International,Women's World Cup,female,False,True,2023,2026-05-03T13:51:31.021141,2026-05-03T13:55:52.303219,2026-05-03T13:55:52.303219,2026-05-03T13:51:31.021141
79,72,30,International,Women's World Cup,female,False,True,2019,2026-05-15T15:31:40.299642,2021-06-13T16:17:31.694,None,2026-05-15T15:31:40.299642

In [ ]:
comeptitions_analysis()

Total entries: 80
Unique competitions: 24
Unique seasons: 48
Countires: 13
Entries from bundesliga: 2
Competition with most entries: Women's World Cup